# Generated by Django 4.2.4 on 2023-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("recipes", "0004_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tag.tag"),
        ),
    ]
